name: Build Next.js Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    env:
      PORT: ${{ secrets.PORT }}
      BACKEND_URL: ${{ secrets.BACKEND_URL }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # o '20' si usas Node 20

      - name: Instalar dependencias
        run: npm install --legacy-peer-deps

      # - name: Build de producción
      #   run: npm run build

      # Si usas `next export` en vez de `next start`, activa esto:
      # - name: Exportar estáticos
      #   run: npm run export

      - name: Guardar artefactos del build (opcional)
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next
